# Generated by Django 6.0.1 on 2026-01-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz_obeda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Стоимость'),
        ),
    ]
