# Generated by Django 6.0.1 on 2026-01-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz_obeda', '0003_dish_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingridients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название ингридиента')),
                ('is_allergen', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Ингридиент',
                'verbose_name_plural': 'Ингридиенты',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='ingridients',
            field=models.ManyToManyField(blank=True, to='zakaz_obeda.ingridients', verbose_name='Ингридиенты'),
        ),
    ]
