# Generated by Django 6.0.1 on 2026-02-02 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz_obeda', '0004_ingridients_dish_ingridients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория отзыва',
                'verbose_name_plural': 'Категории отзыва',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название меню')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Show_application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название заявки')),
            ],
            options={
                'verbose_name': 'Отображение заявки',
                'verbose_name_plural': 'Отображение заявок',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='in_menu',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название заявки')),
                ('date', models.FloatField(blank=True, null=True, verbose_name='Дата')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Стоимость')),
                ('select_dishes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zakaz_obeda.dish', verbose_name='Выбор блюд')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название отзыва')),
                ('sender', models.CharField(max_length=100, unique=True, verbose_name='Имя отправителя')),
                ('about', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_good', models.FloatField(blank=True, null=True, verbose_name='Оценка')),
                ('feedback_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zakaz_obeda.feedback_category', verbose_name='Категория отзыва')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['name'],
            },
        ),
    ]
