# Generated by Django 6.0.1 on 2026-02-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz_obeda', '0005_feedback_category_menu_show_application_dish_in_menu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='СomplexDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название комплекса')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Стоимость')),
                ('about', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('in_menu', models.BooleanField(default=False, verbose_name='В архиве')),
            ],
            options={
                'verbose_name': 'Комплекс',
                'verbose_name_plural': 'Комплексы',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Show_application',
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('DONE', 'Оплата проведена')], default='NEW', max_length=9, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='menu',
            name='dishes',
            field=models.ManyToManyField(blank=True, to='zakaz_obeda.dish', verbose_name='Блюда в меню'),
        ),
        migrations.AlterField(
            model_name='application',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='in_menu',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
        migrations.AddField(
            model_name='сomplexdish',
            name='dishes',
            field=models.ManyToManyField(blank=True, to='zakaz_obeda.dish', verbose_name='Блюда в комплексе'),
        ),
        migrations.AddField(
            model_name='menu',
            name='complex_dishes',
            field=models.ManyToManyField(blank=True, to='zakaz_obeda.сomplexdish', verbose_name='Комплекс в меню'),
        ),
    ]
