# Generated by Django 6.0.1 on 2026-02-04 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz_obeda', '0008_profile_balans'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название заявки учащегося')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата заявки учащегося')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Стоимость заявки учащегося')),
                ('select_dishes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zakaz_obeda.dish', verbose_name='Выбор блюд')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications_student', to=settings.AUTH_USER_MODEL, verbose_name='Автор заказа учащегося')),
            ],
            options={
                'verbose_name': 'Заявка учащегося',
                'verbose_name_plural': 'Заявки учащегося',
                'ordering': ['name'],
            },
        ),
    ]
