# Generated by Django 6.0.1 on 2026-02-04 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz_obeda', '0009_application_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application_student',
            options={'ordering': ['name'], 'verbose_name': 'Пополнение баланса', 'verbose_name_plural': 'Пополнения баланса'},
        ),
        migrations.RemoveField(
            model_name='application_student',
            name='select_dishes',
        ),
        migrations.AddField(
            model_name='application_student',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кому пополняем баланс'),
        ),
        migrations.AddField(
            model_name='application_student',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('DONE', 'Баланс пополнен')], default='NEW', max_length=9, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='application_student',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма пополнения'),
        ),
        migrations.AlterField(
            model_name='application_student',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата заявки учащегося'),
        ),
        migrations.AlterField(
            model_name='application_student',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Название заявки учащегося'),
        ),
        migrations.AlterField(
            model_name='application_student',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='applications_add_balans', to=settings.AUTH_USER_MODEL, verbose_name='Кому пополняем баланс'),
        ),
    ]
