# Generated by Django 6.0.1 on 2026-02-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz_obeda', '0010_alter_application_student_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('povar', 'Повар'), ('student', 'Школьник'), ('parent', 'Родитель'), ('admin', 'Админ')], default='student', max_length=9, verbose_name='Статус'),
        ),
    ]
