# Generated by Django 6.0.1 on 2026-02-05 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz_obeda', '0011_alter_profile_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['name'], 'verbose_name': 'Заявка на закупку', 'verbose_name_plural': 'Заявки на закупку'},
        ),
        migrations.RemoveField(
            model_name='application',
            name='select_dishes',
        ),
        migrations.AddField(
            model_name='application',
            name='menu',
            field=models.ManyToManyField(blank=True, to='zakaz_obeda.menu', verbose_name='Комплекс в меню'),
        ),
        migrations.AlterField(
            model_name='application',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='На какую дату нужен заказ'),
        ),
        migrations.AlterField(
            model_name='application_student',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто обрабатывает заявку'),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название покупки')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Стоимость')),
                ('status_povar', models.CharField(choices=[('NEW', 'Новый'), ('DONE', 'Заказ выдан')], default='NEW', max_length=20, verbose_name='Статус от повара')),
                ('status_oplaty', models.CharField(choices=[('NEW', 'Новый'), ('IN_PROGRESS', 'Оплата проведена'), ('DONE', 'Заказ получен')], default='NEW', max_length=20, verbose_name='Статус оплаты')),
                ('complex_in_purchase', models.ManyToManyField(blank=True, to='zakaz_obeda.сomplexdish', verbose_name='Комплексы')),
                ('dishes_in_purchase', models.ManyToManyField(blank=True, to='zakaz_obeda.dish', verbose_name='Блюда')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
                'ordering': ['name'],
            },
        ),
    ]
