# Generated by Django 6.0.1 on 2026-02-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz_obeda', '0012_alter_application_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название абонемента')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Стоимость абонемента')),
                ('complex_in_abonement', models.ManyToManyField(blank=True, to='zakaz_obeda.сomplexdish', verbose_name='Комплексы в абонементе')),
                ('dishes_in_abonement', models.ManyToManyField(blank=True, to='zakaz_obeda.dish', verbose_name='Блюда в абонементе')),
            ],
            options={
                'verbose_name': 'Абонемент',
                'verbose_name_plural': 'Абонементы',
                'ordering': ['name'],
            },
        ),
    ]
