# Generated by Django 6.0.1 on 2026-02-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz_obeda', '0013_abonement'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonement',
            name='amount_of_complex',
            field=models.FloatField(blank=True, null=True, verbose_name='Количество комплексов'),
        ),
        migrations.AddField(
            model_name='abonement',
            name='amount_of_dishes',
            field=models.FloatField(blank=True, null=True, verbose_name='Количество блюд'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('CONFIRMED', 'Подтвержден'), ('DONE', 'Получен')], default='NEW', max_length=9, verbose_name='Статус'),
        ),
    ]
