# Generated by Django 6.0.1 on 2026-02-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz_obeda', '0014_abonement_amount_of_complex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Название покупки'),
        ),
    ]
