# Generated by Django 6.0.1 on 2026-02-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz_obeda', '0016_purchase_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balans',
            field=models.IntegerField(blank=True, null=True, verbose_name='Баланс обедов'),
        ),
    ]
