# Generated by Django 6.0.1 on 2026-02-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz_obeda', '0017_alter_profile_balans'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='balans_obedov',
            field=models.IntegerField(blank=True, null=True, verbose_name='Баланс обедов'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='balans',
            field=models.FloatField(blank=True, null=True, verbose_name='Баланс денег'),
        ),
    ]
