# Generated by Django 6.0.1 on 2026-02-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz_obeda', '0018_profile_balans_obedov_alter_profile_balans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='class_group',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='учебный класс'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='телефон родителей'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='телефон'),
        ),
    ]
