# Generated by Django 6.0.1 on 2026-02-06 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz_obeda', '0019_alter_profile_class_group_alter_profile_parent_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='balans_dishes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Баланс блюд'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='abonement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zakaz_obeda.abonement', verbose_name='Абонемент'),
        ),
    ]
