# Generated by Django 6.0.1 on 2026-02-06 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz_obeda', '0020_profile_balans_dishes_purchase_abonement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='abonement',
        ),
        migrations.AddField(
            model_name='application_student',
            name='abonement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zakaz_obeda.abonement', verbose_name='Абонемент'),
        ),
    ]
