# Generated by Django 6.0.1 on 2026-02-06 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz_obeda', '0021_remove_purchase_abonement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['name'], 'verbose_name': 'Заявка на закупку повара', 'verbose_name_plural': 'Заявки на закупку повара'},
        ),
        migrations.AlterField(
            model_name='application_student',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='applications_add_balans', to='zakaz_obeda.profile', verbose_name='Кому пополняем баланс'),
        ),
    ]
