# Generated by Django 6.0.1 on 2026-02-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz_obeda', '0022_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingridients',
            options={'ordering': ['name'], 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['name'], 'verbose_name': 'Покупка еды учеником', 'verbose_name_plural': 'Покупки еды учеником'},
        ),
        migrations.AddField(
            model_name='application',
            name='ingridients',
            field=models.ManyToManyField(blank=True, to='zakaz_obeda.ingridients', verbose_name='Ингредиент'),
        ),
        migrations.AddField(
            model_name='ingridients',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='ingridients',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название ингредиента'),
        ),
    ]
