# Generated by Django 6.0.1 on 2026-02-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz_obeda', '0023_alter_ingridients_options_alter_purchase_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ingridients',
            field=models.ManyToManyField(blank=True, null=True, to='zakaz_obeda.ingridients', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='application',
            name='menu',
            field=models.ManyToManyField(blank=True, null=True, to='zakaz_obeda.menu', verbose_name='Комплекс в меню'),
        ),
    ]
