# Generated by Django 6.0.1 on 2026-02-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz_obeda', '0024_alter_application_ingridients_alter_application_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('COST', 'Расчет стоимости'), ('PAY', 'Оплечен'), ('CONFIRMED', 'Подтвержден'), ('DONE', 'Получен')], default='NEW', max_length=9, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('povar', 'Повар'), ('zakup', 'Закупщик'), ('student', 'Школьник'), ('parent', 'Родитель'), ('admin', 'Админ')], default='student', max_length=9, verbose_name='Статус'),
        ),
    ]
